### ISSUE TITLE
[OOB] Observing error on Docker console

### ISSUE THREAD

**Issue by coisme** [PelionIoT/mbed-cloud-tutorial-python-influxdb#8]
I observe errors on Docker console window. I don't know what these errors mean. In addition, the appearance of the graph looks different from the one on the instruction page. I can see only one product. 

`macOS High Sierra, version 10.13.5`

```
$ docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

<img width="865" alt="screen shot 2018-07-03 at 10 58 48" src="https://user-images.githubusercontent.com/3761826/42194780-96e5c766-7eb0-11e8-9cd7-856c553501fa.png">
<img width="1572" alt="screen shot 2018-07-03 at 10 59 06" src="https://user-images.githubusercontent.com/3761826/42194797-ac03fcee-7eb0-11e8-9865-c0635bf2c05f.png">

**Comment by mbartling** [comment]
@coisme Ahh those errors aren't actually errors. I had issues with docker not displaying log.info or log.debug.

**Comment by mbartling** [comment]
@coisme Fixed. Can you confirm?

**Comment by coisme** [comment]
Yep. Now I can see a similar graph and no error messages.
